feat: infoページの追加
Sports-day/sports-day-panel pull request #106
Opened 2024-10-29 01:27 UTC by Takkun0310

informationのページを追加

2024-10-29 01:44 UTC, testusuke approved these changes
LGTM

昨日話したlayout周りうまく使えていますね！
コンポーネント1,2に関しては `components/information`フォルダーにコンポーネントファイルを作成して実装してください〜！

2024-10-29 01:46 UTC, 1nayu requested changes
~~appディレクトリ上の(auth)と(authenticated)ディレクトリは、それぞれ未認証状態と認証された状態の時にアクセスできるルートになってます
informationページを認証された状態でアクセスできるようにしたい場合、(authenticated)ディレクトリ内にinformationディレクトリを作成してください！~~

2024-10-29 01:47 UTC, testusuke commented
Layoutがルートグループ単位でしか設定できないために、`(information)`として分離しました。

Navigationバーを消したいとのことです

2024-10-29 01:56 UTC, 1nayu approved these changes
LGTM!

2024-10-31 16:22 UTC, 1nayu commented
# LGTM
LGTM

2024-10-31 16:24 UTC, merged